/**
 * Deterministic structured compaction provider.
 *
 * The section layout is derived from the MIT-licensed pi-vcc / pi-blackhole
 * algorithmic compaction lineage, rewritten for omp's SessionEntry and
 * CompactionPreparation model instead of Pi JSONL transcripts.
 */
import type { AgentMessage } from "../../types";
import type { CompactionDetails, CompactionPreparation, CompactionResult } from "../compaction";
import { withOpenAiRemoteCompactionPreserveData } from "../openai";
import { computeFileLists } from "../utils";

const VERSION = 1;
const MAX_GOAL_CHARS = 360;
const MAX_CONTEXT_CHARS = 900;
const MAX_TRANSCRIPT_ITEMS = 18;
const MAX_ITEM_CHARS = 420;
const MAX_LIST_ITEMS = 12;

const SECTION_NAMES = [
	"Session Goal",
	"Files And Changes",
	"Commits",
	"Outstanding Context",
	"User Preferences",
	"Rolling Brief Transcript",
] as const;

/** Metadata stored with compactions generated by the deterministic algorithmic provider. */
export interface AlgorithmicCompactionDetails extends CompactionDetails {
	compactor: "algorithmic";
	version: typeof VERSION;
	sections: readonly (typeof SECTION_NAMES)[number][];
	sourceMessageCount: number;
	previousSummaryUsed: boolean;
	derivedFrom: readonly ["pi-vcc", "pi-observational-memory", "pi-blackhole"];
}

/** Options for deterministic algorithmic compaction. */
export interface AlgorithmicCompactionOptions {
	/** User-provided focus text from `/compact <instructions>`, preserved as context. */
	customInstructions?: string;
	/** Extra context supplied by compaction hooks and memory backends. */
	extraContext?: readonly string[];
	/** Opaque preservation payload supplied by hooks. */
	preserveData?: Record<string, unknown>;
}

/** Generate a zero-LLM structured compaction result from prepared session data. */
export function compactAlgorithmically(
	preparation: CompactionPreparation,
	options: AlgorithmicCompactionOptions = {},
): CompactionResult<AlgorithmicCompactionDetails> {
	const sourceMessages = preparation.messagesToSummarize.concat(preparation.turnPrefixMessages);
	const transcriptMessages = sourceMessages.concat(preparation.recentMessages);
	const { readFiles, modifiedFiles } = computeFileLists(preparation.fileOps);
	const summary = renderSections([
		["Session Goal", renderSessionGoal(transcriptMessages)],
		["Files And Changes", renderFilesAndChanges(readFiles, modifiedFiles)],
		["Commits", renderCommits(sourceMessages)],
		["Outstanding Context", renderOutstandingContext(preparation, options)],
		["User Preferences", renderUserPreferences(transcriptMessages)],
		["Rolling Brief Transcript", renderRollingTranscript(transcriptMessages)],
	]);

	const details: AlgorithmicCompactionDetails = {
		compactor: "algorithmic",
		version: VERSION,
		sections: SECTION_NAMES,
		sourceMessageCount: sourceMessages.length,
		previousSummaryUsed: Boolean(preparation.previousSummary),
		derivedFrom: ["pi-vcc", "pi-observational-memory", "pi-blackhole"],
		readFiles,
		modifiedFiles,
	};

	return {
		summary,
		shortSummary: renderShortSummary(transcriptMessages),
		firstKeptEntryId: preparation.firstKeptEntryId,
		tokensBefore: preparation.tokensBefore,
		details,
		preserveData: mergePreserveData(preparation.previousPreserveData, options.preserveData),
	};
}

/**
 * Carry forward non-OpenAI extension state from the previous compaction entry
 * and overlay any hook-supplied payload from this run.
 *
 * The LLM compactor uses `withOpenAiRemoteCompactionPreserveData(previous, undefined)`
 * for the same reason: strip the stale openai-remote-compaction key (we are not
 * issuing a remote compaction call) while keeping other extension/session state.
 * Hook payloads from `options.preserveData` win on key collision so extensions can
 * actively update the data they wrote on the prior turn.
 */
function mergePreserveData(
	previous: Record<string, unknown> | undefined,
	current: Record<string, unknown> | undefined,
): Record<string, unknown> | undefined {
	const carriedOver = withOpenAiRemoteCompactionPreserveData(previous, undefined);
	if (!carriedOver && !current) return undefined;
	if (!current) return carriedOver;
	if (!carriedOver) return current;
	return { ...carriedOver, ...current };
}

function renderSections(sections: readonly (readonly [string, string])[]): string {
	return sections.map(([name, body]) => `[${name}]\n${body.trim() || "None captured."}`).join("\n\n");
}

function renderSessionGoal(messages: readonly AgentMessage[]): string {
	const userMessages = messages
		.filter(message => message.role === "user")
		.map(messageText)
		.filter(Boolean);
	const initial = clip(userMessages[0] ?? "No explicit user goal captured.", MAX_GOAL_CHARS);
	const latest = userMessages.length > 1 ? clip(userMessages[userMessages.length - 1], MAX_GOAL_CHARS) : undefined;
	if (!latest || latest === initial) return `Initial request: ${initial}`;
	return [`Initial request: ${initial}`, `Latest user request: ${latest}`].join("\n");
}

function renderFilesAndChanges(readFiles: readonly string[], modifiedFiles: readonly string[]): string {
	const lines: string[] = [];
	if (modifiedFiles.length > 0) lines.push("Modified files:", ...formatList(modifiedFiles));
	if (readFiles.length > 0) lines.push("Read-only files:", ...formatList(readFiles));
	return lines.length > 0 ? lines.join("\n") : "No file operations captured in the compacted range.";
}

function renderCommits(messages: readonly AgentMessage[]): string {
	const candidates = uniqueLines(
		messages
			.flatMap(message => messageText(message).split("\n"))
			.map(line => sanitize(line).trim())
			.filter(line => /\b(?:commit|committed|fixes|sha|[0-9a-f]{7,40})\b/i.test(line)),
	);
	return candidates.length > 0
		? formatList(candidates.map(line => clip(line, MAX_ITEM_CHARS))).join("\n")
		: "No commits captured.";
}

function renderOutstandingContext(preparation: CompactionPreparation, options: AlgorithmicCompactionOptions): string {
	const lines: string[] = [];
	if (options.customInstructions?.trim()) {
		lines.push(`Compaction focus: ${clip(options.customInstructions, MAX_CONTEXT_CHARS)}`);
	}
	if (preparation.previousSummary?.trim()) {
		lines.push("Previous compaction summary to preserve:", clip(preparation.previousSummary, MAX_CONTEXT_CHARS));
	}
	if (options.extraContext && options.extraContext.length > 0) {
		lines.push("Additional context:", ...formatList(options.extraContext.map(item => clip(item, MAX_CONTEXT_CHARS))));
	}
	const pendingAssistantQuestion = findLastAssistantQuestion(
		preparation.messagesToSummarize.concat(preparation.turnPrefixMessages, preparation.recentMessages),
	);
	if (pendingAssistantQuestion) lines.push(`Last assistant question/request: ${pendingAssistantQuestion}`);
	return lines.length > 0 ? lines.join("\n") : "No unresolved blockers or handoff caveats captured.";
}

function renderUserPreferences(messages: readonly AgentMessage[]): string {
	const preferenceLines = uniqueLines(
		messages
			.filter(message => message.role === "user")
			.flatMap(message => messageText(message).split("\n"))
			.map(line => sanitize(line).trim())
			.filter(line =>
				/\b(?:prefer|preference|always|never|avoid|do not|don't|use|stick to|must|should)\b/i.test(line),
			),
	).map(line => clip(line, MAX_ITEM_CHARS));
	return preferenceLines.length > 0
		? formatList(preferenceLines).join("\n")
		: "No explicit user preferences captured.";
}

function renderRollingTranscript(messages: readonly AgentMessage[]): string {
	const start = Math.max(0, messages.length - MAX_TRANSCRIPT_ITEMS);
	const lines: string[] = [];
	for (let index = start; index < messages.length; index++) {
		const message = messages[index];
		const text = clip(messageText(message), MAX_ITEM_CHARS);
		if (!text) continue;
		lines.push(`- ${roleLabel(message)}: ${text}`);
	}
	return lines.length > 0 ? lines.join("\n") : "No transcript items captured.";
}

function renderShortSummary(messages: readonly AgentMessage[]): string {
	const firstUser = messages.find(message => message.role === "user");
	if (!firstUser) return "Algorithmic compaction";
	return clip(messageText(firstUser).replace(/\s+/g, " "), 120) || "Algorithmic compaction";
}

function findLastAssistantQuestion(messages: readonly AgentMessage[]): string | undefined {
	for (let index = messages.length - 1; index >= 0; index--) {
		const message = messages[index];
		if (message.role !== "assistant") continue;
		const text = messageText(message).trim();
		if (!text) continue;
		const lastLine = text
			.split("\n")
			.map(line => line.trim())
			.filter(Boolean)
			.at(-1);
		if (lastLine?.endsWith("?")) return clip(lastLine, MAX_ITEM_CHARS);
	}
	return undefined;
}

function formatList(items: readonly string[]): string[] {
	const shown = items.slice(0, MAX_LIST_ITEMS).map(item => `- ${item}`);
	if (items.length > MAX_LIST_ITEMS) shown.push(`- … (${items.length - MAX_LIST_ITEMS} more omitted)`);
	return shown;
}

function uniqueLines(lines: readonly string[]): string[] {
	const seen = new Set<string>();
	const result: string[] = [];
	for (const line of lines) {
		if (!line || seen.has(line)) continue;
		seen.add(line);
		result.push(line);
	}
	return result;
}

function messageText(message: AgentMessage): string {
	if (!("content" in message)) return "";
	return contentText(message.content);
}

function contentText(content: unknown): string {
	if (typeof content === "string") return sanitize(content);
	if (!Array.isArray(content)) return "";
	const parts: string[] = [];
	for (const part of content) {
		if (!isRecord(part)) continue;
		const type = part.type;
		if (type === "text" && typeof part.text === "string") {
			parts.push(sanitize(part.text));
		} else if (type === "image") {
			parts.push(`[image: ${typeof part.mimeType === "string" ? part.mimeType : "unknown"}]`);
		} else if (type === "toolCall") {
			parts.push(renderToolCall(part));
		}
	}
	return parts.join("\n");
}

function renderToolCall(part: Record<string, unknown>): string {
	const name = typeof part.name === "string" ? part.name : "tool";
	const args = isRecord(part.arguments) ? part.arguments : undefined;
	const path = args && typeof args.path === "string" ? ` ${args.path}` : "";
	return `[tool call: ${name}${path}]`;
}

function roleLabel(message: AgentMessage): string {
	switch (message.role) {
		case "user":
			return "User";
		case "assistant":
			return "Assistant";
		case "toolResult":
			return "Tool result";
		default:
			return message.role;
	}
}

function clip(text: string, maxChars: number): string {
	const clean = sanitize(text).replace(/\s+/g, " ").trim();
	if (clean.length <= maxChars) return clean;
	return `${clean.slice(0, Math.max(0, maxChars - 1)).trimEnd()}…`;
}

function sanitize(text: string): string {
	return text
		.replace(/\r\n/g, "\n")
		.replace(/\r/g, "\n")
		.replace(/\t/g, "  ")
		.replace(/\x1b\[[0-9;]*[A-Za-z]/g, "")
		.replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g, "");
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null;
}
